# Generated by Django 5.0.6 on 2024-07-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_display_in_home_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('banner', models.ImageField(upload_to='')),
                ('position', models.CharField(choices=[('top', 'top'), ('lower', 'lower'), ('middle', 'middle'), ('left', 'left')], max_length=50)),
            ],
        ),
    ]
