# Generated by Django 5.0.6 on 2024-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='position',
            field=models.CharField(choices=[('top', 'top'), ('lower', 'lower'), ('middle', 'middle'), ('left', 'left'), ('category_page_banner', 'category_page_banner')], max_length=50),
        ),
    ]
